### ISSUE TITLE
Intent to relicense under MIT license

### ISSUE THREAD

**Issue by djzort** [djzort/Net-DHCP#11]
See also https://en.wikipedia.org/wiki/MIT_License and https://metacpan.org/pod/Software::License::MIT

Contributors need to sign off:

@njtaylor n/a
@kyzn yes
@rfdrake yes
@shadowwa yes
@robertlandrum yes

Plus prior authors and contributors TBD

SHADINGER contacted by email and has given all his copyrights to me.

**Comment by robertlandrum** [comment]
LGTM

**Comment by djzort** [comment]
Prior releases on CPAN by FVANDUN and SHADINGER

SHADINGER may be @hadinger

**Comment by rfdrake** [comment]
I'm fine with the relicense to MIT.

**Comment by djzort** [comment]
FVANDUN email bounces

**Comment by shadowwa** [comment]
I'm ok with this license.

**Comment by kyzn** [comment]
Thanks for the ping! I'm also OK with the license change 🎉

**Comment by djzort** [comment]
Contributions from @njtaylor are no longer in Net::DHCP so no need for sign off.

**Comment by djzort** [comment]
I have been unable to contact FVANDUN who made the earliest release of Net::DHCP on the cpan https://metacpan.org/release/FVANDUN/Net-DHCP-0.11

Email listed here bounces https://metacpan.org/author/FVANDUN

**Comment by djzort** [comment]
Everyone has confirmed.

**Comment by djzort** [comment]
Release dev release v0.7_010 to the CPAN with licensed as MIT. Closing.
