### ISSUE TITLE
Net::DHCP::Options doesn't exist

### ISSUE THREAD

**Issue by choroba** [djzort/Net-DHCP#9]
But the documentation links to it several times from the "SEE ALSO" section ([Net::DHCP](https://github.com/djzort/Net-DHCP/blob/master/lib/Net/DHCP.pm#L33), [Net::DHCP::Packet::IPv4Utils](https://github.com/djzort/Net-DHCP/blob/master/lib/Net/DHCP/Packet/IPv4Utils.pm#L117), [Net::DHCP::Constants](https://github.com/djzort/Net-DHCP/blob/master/lib/Net/DHCP/Constants.pm#L808), [Net::DHCP::Packet](https://github.com/djzort/Net-DHCP/blob/master/lib/Net/DHCP/Packet.pm#L1373)).

**Comment by djzort** [comment]
This was probably because of dev releases. Its all on cpan now https://metacpan.org/pod/Net::DHCP::Packet::IPv4Utils
